#!/bin/sh

set -eu

d=data
outdir=$d

./plot_intervals_infected.py --dataFolder "$d" --output_dir "$outdir"
./plot_effective_growth.py --dataDir "$d" --output "$outdir/growth.pdf"

pretty=$d/_korali_samples_pretty
./pretty_samples.py "$d/_korali_samples" "$pretty"
python -m korali.plotter --dir "$pretty"  --output "$outdir/samples.png"
