#!/bin/bash

set -eu

for f in */intervals.json ; do
  d=${f%/*}
  echo $d
  outfile=$d/growth.pdf
  if [ -f "$outfile" ] ; then
    echo "skip existing '$outfile'"
    continue
  fi
  ./plot_effective_growth.py --dataDir "$d" --output "$d/growth.pdf" --title "$d"
done

for f in */_korali_samples ; do
  d=${f%/*}
  echo $d
  outfile=$d/samples.png
  if [ -f "$outfile" ] ; then
    echo "skip existing '$outfile'"
    continue
  fi
  pretty=$d/_korali_samples_pretty
  ./pretty_samples.py "$d/_korali_samples" "$pretty"
  python -m korali.plotter --dir "$pretty" --output "$d/samples.png" > /dev/null || true
  echo "$d/samples.png"
done
